// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Add Items to Cart Tab and Landing to Cart Tab', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Add Items to Cart Tab and Landing to Cart Tab', async function() {
    await driver.get("http://localhost:3000/restaurantdetailpagedesktop")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".focus\\3Ascale-300")).click()
    await driver.findElement(By.css(".gap-5:nth-child(4) > .bg-gray-50_02:nth-child(4) .h-\\[49px\\]")).click()
    await driver.findElement(By.css(".sm\\3A flex-col > .common-pointer .h-\\[49px\\]")).click()
    await driver.findElement(By.css(".h-6")).click()
  })
})
