// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Calculate Route and Save Destination', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Calculate Route and Save Destination', async function() {
    await driver.get("http://localhost:3000/map")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".pac-target-input")).click()
    // await driver.findElement(By.css(".pac-target-input")).sendKeys("hapugala, ")
    // {
    //   const element = await driver.findElement(By.css("div:nth-child(2) > .bg-orange-600_cc:nth-child(2)"))
    //   await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    // }
    // assert(await driver.switchTo().alert().getText() == "Destination saved successfully!")
  })
})
