// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Google Reviews and See Gallery', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Google Reviews and See Gallery', async function() {
    await driver.get("http://localhost:3000/restaurantdetailpagedesktop")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".text-black-900:nth-child(4)")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // await driver.findElement(By.linkText("Free Google Reviews widget")).click()
    // vars["win4949"] = await waitForWindow(2000)
    // vars["root"] = await driver.getWindowHandle()
    // await driver.switchTo().window(vars["win4949"])
    // await driver.switchTo().window(vars["root"])
    // await driver.findElement(By.css(".image-wrapper:nth-child(7) > .h-80")).click()
  })
})
