// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Increase and Decrease Quantity of Cart Items', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Increase and Decrease Quantity of Cart Items', async function() {
    await driver.get("http://localhost:3000/orderingpage")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    // await driver.findElement(By.css(".bg-gray-50_02:nth-child(2) .arrow-button:nth-child(1) path")).click()
    // await driver.findElement(By.css(".bg-gray-50_02:nth-child(2) .arrow-button:nth-child(1) path")).click()
    // await driver.findElement(By.css(".bg-gray-50_02:nth-child(2) .arrow-button:nth-child(1) path")).click()
    // await driver.findElement(By.css(".bg-gray-50_02:nth-child(2) .arrow-button:nth-child(3) > .svg-inline--fa")).click()
    // await driver.findElement(By.css(".bg-gray-50_02:nth-child(2) .arrow-button:nth-child(3) path")).click()
  })
})
