// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login (Positive Scenario) and Logout', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login (Positive Scenario) and Logout', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".nav-button:nth-child(2)")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("hirunadesilva0422@gmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("Hiruna#72")
    await driver.findElement(By.name("password")).sendKeys(Key.ENTER)
    // await driver.findElement(By.css(".gap-3")).click()
  })
})
