// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login to Home Tab and Navigate to Restaurant Tab', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login to Home Tab and Navigate to Restaurant Tab', async function() {
    await driver.get("http://localhost:3000/loginorreg")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("hirunadesilva0422@gmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("Hiruna#72")
    await driver.findElement(By.name("password")).sendKeys(Key.ENTER)
    // await driver.findElement(By.css(".font-medium:nth-child(2)")).click()
  })
})
