// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login (Invalid Email)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login (Invalid Email)', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("Kavindu")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("username")
    await driver.findElement(By.css(".sc-qZrbh")).click()
  })
})
